### ISSUE TITLE
Tried on a GenoPro .ged file and got an error

### ISSUE THREAD

**Issue by beaugunderson** [tmcw/gedcom#1]
The source of the error was that a link node was generated with no `target` attribute, I fixed locally by filtering `links` by checking that both source and target were defined but am not sending a PR since I didn't figure out the underlying issue.

[Here's a screenshot of the rendered graph](http://cl.ly/image/2x0T2K223f16) which I thought was pretty cool.

By way of explanation for why I've now popped up a second time in your projects, I'm a huge fan of JavaScript mapping & also of genealogy and saw this repo in my GitHub timeline. Also, madprime is my coworker and I noticed you use the regex from her repo--super small world!

**Comment by tmcw** [comment]
Interesting! And now I realize that debugging gedcom parsers will be interesting since all the data they process is privacy-sensitive :)

Does madprime's code work with your data? With the filter, can you try to narrow down where the bad pointer is coming from?

**Comment by beaugunderson** [comment]
Hmm, there are actually a ton of them, starting at node 690 and continuing for a couple of hundred nodes. I exported a version with privacy enabled (living individuals are stripped of information except names) and don't have a problem sharing that (it's already online); [here it is](https://dl.dropboxusercontent.com/u/19435/privacy.ged). It seems like many of the nodes without targets are family nodes.

Haven't tried this file with python-gedcom; are you just curious if it parses at all?

**Comment by tmcw** [comment]
Try 1.0.3 - issue looks like

```
0 @F006@ FAM
1 HUSB @I0011@
1 WIFE @I0012@
1 CHIL @ind00009@
1 CHIL @ind00551@
1 MARR <- this is not a connection, it is metadata
```

Added a simple check to make sure that we're connecting pointers only.

**Comment by beaugunderson** [comment]
1.0.3 fixes it!
