### ISSUE TITLE
Serializer

### ISSUE THREAD

**Issue by davidenke** [tmcw/gedcom#20]
@tmcw do you know any serializers to bring JSON back to the `*.ged` format? Will it make sense to build it into this package?

**Comment by tmcw** [comment]
Hey David,

I don't know of any currently - what `parse-gedcom` generates is pretty basic and not a fully standardized syntax. I've been working on a [2.0 version](https://beta.observablehq.com/@tmcw/parse-gedcom) and recently went looking for a gedcom spec, and there's… [gedcomx](http://www.gedcomx.org/). Which is really making me wonder - should 2.0 produce (and maybe consume?) gedcomx, or is it one of those overbuilt standards that sort of went off the rails. I'm pretty divided on it - implementing gedcomx support seems like a good long-term move but would also make 2.0 a much larger endeavor, and I'm not sure if there's any uptake of gedcomx anyway.

So... long answer is also an "I'm not sure" - whether this is the right path forward, and whether implementing a fully spec-compliant gedcomx translator is something I have the time & focus to do.

**Comment by davidenke** [comment]
Thanks @tmcw for your response.
In this case I'll implement a simple custom serializer fitting to my purposes.
