### ISSUE TITLE
Trailing blanks are stripped from notes

### ISSUE THREAD

**Issue by woodbri** [tmcw/gedcom#22]
In NOTE records CONC and CONT lines may or may not have a trailing blank character depending on the context of the note. This is getting stripped off and it messes up the results when reconstructing the NOTE message. IE: the trailing blank if it exists is significant and should not be removed.

I changed line 60 in index.js to say:

    data: match[4].trimLeft(),

And this fixes the problem and does not appear to break anything else.

**Comment by tmcw** [comment]
Thanks - just pushed an update and this is fixed in 1.0.4!
