### ISSUE TITLE
Syntax error near unexpected token `('

### ISSUE THREAD

**Issue by jarmolukd** [tmcw/gedcom#39]
When I try to run the following:

`parse-gedcom test.ged test.json`

I get the following:

`/usr/local/bin/parse-gedcom: line 1: syntax error near unexpected token `('
/usr/local/bin/parse-gedcom: line 1: `var e=require("fs"),t=require("path"),r=require("meow"),n=require("get-stdin"),E=require("unist-util-visit-parents"),a=require("unist-util-remove"),A=require("graphlib-dot"),i=require("graphlib");function I(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var o=I(e),N=I(t),R=I(r),u=I(n),T=I(E),l=I(a),S=I(A);function O(e,t){(null==t||t>e.length)&&(t=e.length);for(var r=0,n=new Array(t);r<t;r++)n[r]=e[r];return n}function C(e,t){var r;if("undefined"==typeof Symbol||null==e[Symbol.iterator]){if(Array.isArray(e)||(r=function(e,t){if(e){if("string"==typeof e)return O(e,t);var r=Object.prototype.toString.call(e).slice(8,-1);return"Object"===r&&e.constructor&&(r=e.constructor.name),"Map"===r||"Set"===r?Array.from(e):"Arguments"===r||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(r)?O(e,t):void 0}}(e))||t&&e&&"number"==typeof e.length){r&&(e=r);var n=0;return function(){return n>=e.length?{done:!0}:{done:!1,value:e[n++]}}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}return(r=e[Symbol.iterator]()).next.bind(r)}var f=new RegExp("^([0-9]*)"),d=new RegExp("(\\s+)"),c=new RegExp("^(["+d+"])"),s=new RegExp("^@([A-ZÀ-ÿa-z_0-9])([A-ZÀ-ÿa-z_0-9"+d+"#])*@"),v=new RegExp("^(_?[A-ZÀ-ÿa-z_0-9]+)"),M=new RegExp(/^(.*)/);function D(e){function t(t,r){var n=e.match(t);if(!n)throw new Error(r);return e=e.substring(n[0].length),n[1]}e=e.trimStart();var r=void 0,n=t(f,"Expected level");if(n.length>2||2===n.length&&"0"===n[0])throw new Error("Invalid level: "+n);var E=parseInt(n);t(c,"Expected delimiter after level");var a=e.match(s);a&&(r=a[0],e=e.substring(a[0].length),t(c,"Expected delimiter after pointer"));var A={level:E,tag:t(v,"Expected tag")};r&&(A.xref_id=r);var i=e.match(c);if(i){var I=(e=e.substring(i[0].length)).match(s),o=e.match(M);I?A.pointer=I[0]:o&&(A.value=o[1])}return A}var L={ABBR:"ABBREVIATION",ADDR:"ADDRESS",ADR1:"ADDRESS1",ADR2:"ADDRESS2",ADOP:"ADOPTION",AFN:"AFN",AGE:"AGE",AGNC:"AGENCY",ALIA:"ALIAS",ANCE:"ANCESTORS",ANCI:"ANCES_INTEREST",ANUL:"ANNULMENT",ASSO:"ASSOCIATES",AUTH:"AUTHOR",BAPL:"BAPTISM-LDS",BAPM:"BAPTISM",BARM:"BAR_MITZVAH",BASM:"BAS_MITZVAH",BIRT:"BIRTH",BLES:"BLESSING",BURI:"BURIAL",CALN:"CALL_NUMBER",CAST:"CASTE",CAUS:"CAUSE",CENS:"CENSUS",CHAN:"CHANGE",CHAR:"CHARACTER",CHIL:"CHILD",CHR:"CHRISTENING",CHRA:"ADULT_CHRISTENING",CITY:"CITY",CONC:"CONCATENATION",CONF:"CONFIRMATION",CONL:"CONFIRMATION_LDS",CONT:"CONTINUED",COPR:"COPYRIGHT",CORP:"CORPORATE",CREM:"CREMATION",CTRY:"COUNTRY",DATA:"DATA",DATE:"DATE",DEAT:"DEATH",DESC:"DESCENDANTS",DESI:"DESCENDANT_INT",DEST:"DESTINATION",DIV:"DIVORCE",DIVF:"DIVORCE_FILED",DSCR:"PHY_DESCRIPTION",EDUC:"EDUCATION",EMAI:"EMAIL",EMIG:"EMIGRATION",ENDL:"ENDOWMENT",ENGA:"ENGAGEMENT",EVEN:"EVENT",FACT:"FACT",FAM:"FAMILY",FAMC:"FAMILY_CHILD",FAMF:"FAMILY_FILE",FAMS:"FAMILY_SPOUSE",FAX:"FACIMILIE",FCOM:"FIRST_COMMUNICATION",FILE:"FILE",FORM:"FORMAT",FONE:"PHONETIC",GEDC:"GEDCOM",GIVN:"GIVEN_NAME",GRAD:"GRADUATION",HEAD:"HEADER",HUSB:"HUSBAND",IDNO:"IDENT_NUMVER",IMMI:"IMMIGRATION",INDI:"INDIVIDUAL",LANG:"LANGUAGE",LATI:"LATITUDE",LONG:"LONGITUDE",MAP:"MAP",MARB:"MARRIAGE_BANN",MARC:"MARRIAGE_CONTRACT",MARL:"MARRIAGE_LICENSE",MARR:"MARRIAGE",MARS:"MARRIAGE_SETTLEMENT",MEDI:"MEDIA",NAME:"NAME",NATI:"NATIONALITY",NATU:"NATURALIZATION",NCHI:"CHILDREN_COUNT",NICK:"NICKNAME",NMR:"MARRIAGE_COUNT",NOTE:"NOTE",NPFX:"NAME_PREFIX",NSFX:"NAME_SUFFIX",OBJE:"OBJECT",OCCU:"OCCUPATION",ORDI:"ORDINANCE",ORDN:"ORDINATION",PAGE:"PAGE",PEDI:"PEDIGREE",PHON:"PHONE",PLAC:"PLACE",POST:"POSTAL_CODE",PROB:"PROBATE",PROP:"PROPERTY",PUBL:"PUBLICATION",QUAY:"QUALITY_OF_DATA",REFN:"REFERENCE",RELA:"RELATIONSHIP",RELI:"RELIGION",REPO:"REPOSITORY",RESI:"RESIDENCE",RESN:"RESTRICTION",RETI:"RETIREMENT",RFN:"REC_FILE_NUMBER",RIN:"REC_ID_NUMBER",ROLE:"ROLE",ROMN:"ROMANIZED",SEX:"SEX",SLGC:"SEALING_CHILD",SLGS:"SEALING_SPOUCE",SOUR:"SOURCE",SPFX:"SURN_PREFIX",SSN:"SURN_PREFIX",STAE:"STATE",STAT:"STATUS",SUBM:"SUBMITTER",SUBN:"SUBMISSION",SURN:"SURNAME",TEMP:"TEMPLE",TEXT:"TEXT",TIME:"TIME",TITL:"TITLE",TRLR:"TRAILER",TYPE:"TYPE",VERS:"VERSION",WIFE:"WIFE",WILL:"WILL",WWW:"WEB"},p=new RegExp("(\\r|\\n|\\r\\n|\\n\\r)","g");function U(e){var t=e.tag,r=e.xref_id,n=e.pointer,E={type:t,data:{formal_name:L[t]},value:e.value,children:[]};return r&&(E.data.xref_id=r),n&&(E.data.pointer=n),t.startsWith("_")&&(E.data.custom_tag=!0),E}function h(e,t){var r=e.tag,n=e.value;if("CONC"!==r&&"CONT"!==r)return!1;if(e.pointer)throw new Error("Cannot concatenate a pointer");return t.value||(t.value=""),"CONT"===r&&(t.value+="\n"),n&&(t.value+=n),!0}function P(e,t,r){e[t]?e["+"+t]=(e["+"+t]||[]).concat(r):e[t]=r}function _(e){var t=function(e,t){void 0===t&&(t=["TRLR","SUBM","SUBN","HEAD","NOTE","SOUR"]),l.default(e,t);for(var r,n=function(){var e=r.value;e.data||(e.data={}),T.default(e,function(t,r){var n,E=r.slice(1).concat(t).map(function(e){var t;return(null==(t=e.data)?void 0:t.formal_name)||e.type}).join("/");t.value?P(e.data,E,t.value):null!=(n=t.data)&&n.pointer&&P(e.data,"@"+E,t.data.pointer)}),e.children=[]},E=C(e.children);!(r=E()).done;)n();return e}(e).children,r=new Set(t.map(function(e){var t;return null==(t=e.data)?void 0:t.xref_id}).filter(Boolean)),n=[],E=new Map;return t.forEach(function(e){e.data&&Object.entries(e.data).filter(function(e){return e[0].startsWith("@")}).forEach(function(t){var a,A,i=t[0],I=t[1];if(!r.has(I))throw new Error("Undefined reference: "+I);if(null==(a=e.data)||!a.xref_id)throw new Error("Link from node with no xref id");var o=null==(A=e.data)?void 0:A.xref_id,N=I,R={source:o,target:N,value:i};n.push(R);var u=[o,N].sort().join("/");E.has(u)?E.get(u).push(R):E.set(u,[R])})}),function(e,t){for(var r,n=[["@HUSBAND","@FAMILY_SPOUSE"],["@WIFE","@FAMILY_SPOUSE"],["@FAMILY_CHILD","@CHILD"]],E=function(){var e=r.value[1];n.forEach(function(r){var n=r.map(function(t){return e.find(function(e){return e.value==t})}),E=n[0];E&&n[1]&&t.splice(t.indexOf(E),1)})},a=C(e);!(r=a()).done;)E()}(E,n),{nodes:t,links:n}}var g=R.default("\n\tUsage\n\t  $ parse-gedcom <input>\n\tOptions\n\t  --type, -s   Output type (json, d3.json, dot)\n\tExamples\n\t  $ parse-gedcom input.ged output.json\n",{flags:{type:{type:"string",alias:"t"}}}),F={".json":"json",".d3.json":"force",".dot":"dot"};!function(){try{var e=function(e){var t=function(e){for(var t,r={type:"root",children:[]},n=[],E=0,a=C(e.split(p).filter(function(e){return e.trim()}));!(t=a()).done;){var A=D(t.value);if(!h(A,n[n.length-1])){var i=U(A),I=A.level;if(0==I)r.children.push(i),n=[i];else{if(!(E==I-1||I<=E))throw new Error("Illegal nesting: transition from "+E+" to "+I);for(var o=0;o<=E-I;o++)n.pop();n[n.length-1].children.push(i),n.push(i)}E=I}}return r}(e),r="json";if(g.flags.type)r=g.flags.type;else if(n){var E=N.default.extname(n);E in F&&(r=F[E])}var a="";switch(r){case"json":return void(a=JSON.stringify(t,null,2));case"d3.json":return void(a=JSON.stringify(_(t),null,2));case"dot":return void(a=S.default.write(function(e){for(var t,r=_(e),n=r.nodes,E=r.links,a=new i.Graph,A=C(n);!(t=A()).done;){var I,o=t.value,N=(o.data||{}).NAME;a.setNode(null==(I=o.data)?void 0:I.xref_id,{label:N?N.replace(/^@/,""):o.type})}for(var R,u=C(E);!(R=u()).done;){var T=R.value;a.setEdge(T.source,T.target,{label:T.value})}return a}(t)))}n?o.default.writeFileSync(n,a,"utf8"):process.stdout.write(a)},t=g.input,r=t[0],n=t[1];r?e(o.default.readFileSync(r,"utf8")):Promise.resolve(u.default()).then(e)}catch(e){Promise.reject(e)}}();'`

I've run this with both a very complex/long .ged file and a very simple .ged file. Have also attempted to output to .dot and .json file. Same error results regardless.

**Comment by tmcw** [comment]
Okay, it looks like the generated CLI doesn't include the first line which causes your computer to treat it as a node script. I'll look into it.

**Comment by removed-account-123** [comment]
I have the same error with `2.0.1` version :( but it parsed well my file with `1.0.5`.
