### ISSUE TITLE
Expected Identifier, string or number with Ancestry GED export

### ISSUE THREAD

**Issue by JuliusJacobsohn** [tmcw/gedcom#40]
![image](https://user-images.githubusercontent.com/13764328/111376825-3a8adb00-86a0-11eb-81db-9f3e18f34cbe.png)

I installed the package globally with npm i -g parse-gedcom and executed parse-gedcom Stammbaum.ged output.json.
output.json does not exist in the directory.

**Comment by tmcw** [comment]
Fixed in the same pass as #39. I'll shortly publish a new version as the `gedcom` package.
